apiVersion: v1
kind: ReplicationController
metadata:
  name: security-sys-http-nonprod-rc
spec:
  replicas: 2
  selector:
    app: security-sys-http-nonprod
  template:
    metadata:
      labels:
        app: security-sys-http-nonprod
    spec:
      containers:
      - name: security-sys-http-nonprod-pod
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts: 
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name: default-conf-file
      volumes:
      - name: default-conf-file
        configMap:
          name: sec-sys-http-nonprod-default-conf